# Generated by Django 5.2.17 on 2026-08-15 07:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0002_alter_credentialdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('price_tzs', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['duration_days', 'price_tzs'],
            },
        ),
        migrations.CreateModel(
            name='BadgeSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.badgeplan')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badge_subscriptions', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='CLICKPESA', max_length=40)),
                ('client_reference', models.CharField(max_length=64, unique=True)),
                ('provider_payment_reference', models.CharField(blank=True, db_index=True, max_length=180)),
                ('provider_order_reference', models.CharField(blank=True, db_index=True, max_length=180)),
                ('amount_tzs', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('channel', models.CharField(choices=[('USSD_PUSH', 'USSD Push'), ('BILLPAY', 'BillPay'), ('CARD', 'Card'), ('UNKNOWN', 'Unknown')], default='USSD_PUSH', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=16)),
                ('phone_number', models.CharField(max_length=20)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.badgesubscription')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='CLICKPESA', max_length=40)),
                ('event_name', models.CharField(max_length=80)),
                ('provider_event_id', models.CharField(max_length=180)),
                ('order_reference', models.CharField(blank=True, db_index=True, max_length=180)),
                ('checksum_valid', models.BooleanField(default=False)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-received_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_provider_webhook_event')],
            },
        ),
        migrations.AddIndex(
            model_name='badgesubscription',
            index=models.Index(fields=['professional', 'status', 'ends_at'], name='billing_bad_profess_f85c45_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_order_reference'), name='unique_provider_order_reference'),
        ),
    ]
