# Generated by Django 5.2.17 on 2026-08-15 07:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0002_alter_credentialdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(choices=[('CATTLE', 'Cattle'), ('GOAT', 'Goat'), ('SHEEP', 'Sheep'), ('POULTRY', 'Poultry'), ('DOG', 'Dog'), ('CAT', 'Cat'), ('OTHER', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('identification_code', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='animals.animal')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_veterinary_records', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veterinary_records', to='professionals.clinic')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veterinary_records', to='professionals.professionalprofile')),
            ],
            options={
                'ordering': ['-occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecordAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_access_logs', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='animals.veterinaryrecord')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write')], default='READ', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants_issued', to=settings.AUTH_USER_MODEL)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_grants', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='animals.veterinaryrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['owner', 'species', 'is_active'], name='animals_ani_owner_i_adcd5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('owner', 'identification_code'), name='unique_animal_identifier_per_owner'),
        ),
        migrations.AddIndex(
            model_name='veterinaryrecord',
            index=models.Index(fields=['animal', 'occurred_at'], name='animals_vet_animal__a4408d_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinaryrecord',
            index=models.Index(fields=['author', 'created_at'], name='animals_vet_author__350ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='recordaccesslog',
            index=models.Index(fields=['record', 'occurred_at'], name='animals_rec_record__879e95_idx'),
        ),
        migrations.AddIndex(
            model_name='recordaccessgrant',
            index=models.Index(fields=['grantee', 'revoked_at', 'expires_at'], name='animals_rec_grantee_fd2675_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordaccessgrant',
            constraint=models.UniqueConstraint(fields=('record', 'grantee'), name='unique_record_grantee'),
        ),
    ]
