/* Sunlit Credential workspace shell: a role-aware protected frame keeps profile switching, evidence, and progress visibly connected. */
import { Bell, ChevronDown, Menu, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { BrandMark } from "./BrandMark";
import { CredentialSeal } from "./CredentialSeal";
import { getRoleMeta, roleOptions, useActiveRole } from "@/lib/workspace";
import { LanguageSwitcher } from "./LanguageSwitcher";

const navigation = {
  OWNER: [["overview", "Overview"], ["animals", "Animals & records"], ["care-plan", "Care plan"], ["messages", "Secure messages"], ["community", "Community"], ["tools", "Care tools"]],
  VETERINARIAN: [["overview", "Practice overview"], ["schedule", "Care schedule"], ["cases", "Care relationships"], ["credentials", "Credentials & badge"], ["messages", "Secure messages"], ["tools", "Clinical tools"]],
  CLINIC: [["overview", "Clinic overview"], ["team", "Team readiness"], ["services", "Services & capacity"], ["messages", "Secure messages"], ["credentials", "Clinic verification"], ["community", "Community"]],
  VENDOR: [["overview", "Vendor overview"], ["catalogue", "Catalogue"], ["inventory", "Stock controls"], ["orders", "Enquiries"], ["billing", "Payout readiness"], ["community", "Community"]],
  ADMIN: [["overview", "Network overview"], ["verification", "Verification queue"], ["reports", "Safety reports"], ["operations", "Operations"], ["community", "Community review"], ["messages", "Secure messages"]],
} as const;

export function DashboardShell({ children }: { children: React.ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [location] = useLocation();
  const { role, meta, switchRole } = useActiveRole(); const RoleIcon = meta.icon;
  const links = navigation[role];
  const chooseRole = (nextRole: typeof role) => { switchRole(nextRole); setProfileOpen(false); };
  const sidebar = <aside className="care-contours-dark flex h-full flex-col bg-[#173d30] px-4 py-6 text-[#f9f3e7]"><div className="px-2"><BrandMark tone="dark"/><div className="mt-7 flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#f2d48d] text-[#244c3d]"><RoleIcon size={14}/></span><div><p className="text-[9px] font-extrabold uppercase tracking-[.18em] text-[#d5b76f]">Active profile</p><p className="mt-0.5 text-xs font-extrabold">{meta.label}</p></div></div></div><nav className="mt-7 grid gap-1">{links.map(([module, label]) => { const href = `/portal/${module}`; const active = location === href || (module === "overview" && location === "/portal"); return <Link key={module} href={href} onClick={() => setMobileOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${active ? "bg-[#f5ead3] text-[#1d4537] shadow-[0_10px_20px_-16px_rgba(0,0,0,.6)]" : "text-[#dce6dc] hover:bg-white/10"}`}><span className={`h-1.5 w-1.5 rounded-full ${active ? "bg-[#b78a38]" : "bg-[#dce6dc]/45"}`}/>{label}</Link>; })}</nav><div className="mt-auto rounded-2xl border border-[#e4c570]/35 bg-[#0f3025]/45 p-4"><div className="flex items-center gap-2"><CredentialSeal size={14}/><span className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#e7cb84]">Profile studio</span></div><p className="mt-3 text-xs font-bold leading-5">Switch your workspace when your responsibilities change. Access remains limited by verified backend roles.</p><Link href="/onboarding" onClick={() => setMobileOpen(false)} className="mt-3 inline-block text-xs font-extrabold text-[#e9c675]">Review profiles →</Link></div></aside>;
  return <div className="min-h-screen bg-[#f7f3ea] lg:grid lg:grid-cols-[282px_1fr]"><div className="hidden lg:block">{sidebar}</div>{mobileOpen && <div className="fixed inset-0 z-50 grid grid-cols-[290px_1fr] lg:hidden"><div>{sidebar}</div><button className="bg-[#173d30]/30 backdrop-blur-[2px]" onClick={() => setMobileOpen(false)} aria-label="Close menu"/></div>}<main className="min-w-0"><header className="flex h-[74px] items-center justify-between border-b border-[#e5dac5] bg-[#fcfaf6]/95 px-5 backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><button className="grid h-10 w-10 place-items-center rounded-xl border border-[#e4d7bf] lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open workspace menu"><Menu size={19}/></button><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#9a793e]">Protected workspace</p><p className="hidden text-sm font-bold text-[#244c3d] sm:block">{meta.short} profile · Tanzania & Zanzibar</p></div></div><div className="flex items-center gap-2 sm:gap-3"><LanguageSwitcher compact/><Link href="/portal/notifications" className="pulse-halo grid h-10 w-10 place-items-center rounded-full border border-[#e4d7bf] bg-white text-[#244c3d]" aria-label="Notifications"><Bell size={17}/></Link><div className="relative"><button className="flex items-center gap-2 rounded-full bg-white py-1 pl-1 pr-3 ring-1 ring-[#e4d7bf]" onClick={() => setProfileOpen(!profileOpen)} aria-expanded={profileOpen}><span className="grid h-8 w-8 place-items-center rounded-full bg-[#f1e0b9] text-xs font-extrabold text-[#244c3d]">MK</span><span className="hidden text-xs font-extrabold text-[#244c3d] sm:block">{meta.short}</span><ChevronDown size={14}/></button>{profileOpen && <div className="absolute right-0 top-12 z-40 w-72 rounded-2xl border border-[#e8dcc7] bg-white p-2 shadow-[0_24px_50px_-24px_rgba(35,69,53,.4)]"><p className="px-3 pb-2 pt-1 text-[9px] font-extrabold uppercase tracking-[.16em] text-[#9a793e]">Switch active profile</p>{roleOptions.map((option) => { const Icon = option.icon; return <button key={option.key} onClick={() => chooseRole(option.key)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left transition ${option.key === role ? "bg-[#f7efdC]" : "hover:bg-[#faf6ee]"}`}><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f4e4bf] text-[#315d49]"><Icon size={15}/></span><span><strong className="block text-xs text-[#244c3d]">{option.label}</strong><small className="block text-[10px] text-[#708077]">{option.key === role ? "Current workspace" : "Open view"}</small></span></button>; })}<Link href="/onboarding" className="mt-1 flex items-center gap-2 rounded-xl border border-[#eadfca] px-3 py-2.5 text-xs font-extrabold text-[#8a6727]"><Sparkles size={14}/>Profile studio & guide</Link></div>}</div></div></header>{children}</main></div>;
}
