/* Sunlit Credential workspace shell: private care functions use a deep palm navigation frame with generous, paper-like work surfaces. */
import { Bell, ChevronDown, Menu, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { BrandMark } from "./BrandMark";
import { workspaceLinks } from "@/lib/catalog";
import { CredentialSeal } from "./CredentialSeal";

export function DashboardShell({ children }: { children: React.ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false); const [location] = useLocation();
  const sidebar = <aside className="care-contours-dark flex h-full flex-col bg-[#173d30] px-4 py-6 text-[#f9f3e7]"><div className="px-2"><BrandMark tone="dark" /><p className="mt-7 text-[10px] font-extrabold uppercase tracking-[0.19em] text-[#cbb77c]">Your care space</p></div><nav className="mt-4 grid gap-1">{workspaceLinks.map(({ href, icon: Icon, label }) => <Link key={href} href={href} onClick={() => setMobileOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${location === href ? "bg-[#f5ead3] text-[#1d4537]" : "text-[#dce6dc] hover:bg-white/10"}`}><Icon size={17}/>{label}</Link>)}</nav><div className="mt-auto rounded-2xl border border-[#e4c570]/35 bg-[#0f3025]/45 p-4"><div className="flex items-center gap-2"><CredentialSeal size={14}/><span className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#e7cb84]">Care pathway</span></div><p className="mt-3 text-xs font-bold leading-5">Keep your profile current to help care reach you when it matters.</p><Link href="/portal/kyc" className="mt-3 inline-block text-xs font-extrabold text-[#e9c675]">Review profile →</Link></div></aside>;
  return <div className="min-h-screen bg-[#f7f3ea] lg:grid lg:grid-cols-[270px_1fr]"> <div className="hidden lg:block">{sidebar}</div>{mobileOpen && <div className="fixed inset-0 z-50 grid grid-cols-[280px_1fr] lg:hidden"><div>{sidebar}</div><button className="bg-[#173d30]/30" onClick={() => setMobileOpen(false)} aria-label="Close menu" /></div>}
    <main className="min-w-0"><header className="flex h-[72px] items-center justify-between border-b border-[#e5dac5] bg-[#fcfaf6] px-5 sm:px-8"><div className="flex items-center gap-3"><button className="grid h-10 w-10 place-items-center rounded-xl border border-[#e4d7bf] lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open workspace menu"><Menu size={19}/></button><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#9a793e]">Protected workspace</p><p className="hidden text-sm font-bold text-[#244c3d] sm:block">Your animal care, organised</p></div></div><div className="flex items-center gap-3"><button className="grid h-10 w-10 place-items-center rounded-full border border-[#e4d7bf] text-[#244c3d]" aria-label="Notifications"><Bell size={17}/></button><button className="flex items-center gap-2 rounded-full bg-white py-1 pl-1 pr-3 ring-1 ring-[#e4d7bf]"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#f1e0b9] text-xs font-extrabold text-[#244c3d]">MK</span><span className="hidden text-xs font-extrabold text-[#244c3d] sm:block">My account</span><ChevronDown size={14}/></button></div></header>{children}</main></div>;
}
