# Generated by Manus for email OTP verification.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimetoken",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="onetimetoken",
            index=models.Index(fields=["user", "purpose", "expires_at", "used_at"], name="accounts_otp_verification_idx"),
        ),
    ]
