# Generated by Django 5.2.17 on 2026-08-15 07:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_alter_locality_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=80, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='locations.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_clinics', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='locations.region')),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='locations.servicearea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='professionals.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('professional_type', models.CharField(max_length=40)),
                ('registration_number', models.CharField(max_length=80, unique=True)),
                ('issuing_body', models.CharField(max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professionals', to='locations.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professionals', to='locations.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_reviews', to='professionals.clinic')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=80)),
                ('object_key', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=120)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='professionals.clinic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_documents', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='professionals.professionalprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['region', 'district', 'verification_status'], name='professiona_region__0745b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicstaff',
            constraint=models.UniqueConstraint(fields=('clinic', 'user'), name='unique_clinic_staff'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['region', 'district', 'verification_status', 'is_available'], name='professiona_region__f9eba7_idx'),
        ),
        migrations.AddIndex(
            model_name='kycreview',
            index=models.Index(fields=['decision', 'decided_at'], name='professiona_decisio_295e77_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialdocument',
            index=models.Index(fields=['owner', 'submitted_at'], name='professiona_owner_i_9669bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='credentialdocument',
            constraint=models.CheckConstraint(condition=models.Q(('professional__isnull', False), ('clinic__isnull', False), _connector='OR'), name='credential_has_subject'),
        ),
    ]
