# Generated by Django 5.2.17 on 2026-08-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentialdocument',
            options={'ordering': ['-submitted_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'ordering': ['user__last_name', 'user__first_name', 'id']},
        ),
    ]
