# Generated by Django 5.2.17 on 2026-08-15 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species_code', models.CharField(max_length=40)),
                ('production_category', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('formula_key', models.CharField(max_length=120)),
                ('assumptions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['species_code', 'production_category', '-version'],
                'constraints': [models.UniqueConstraint(fields=('species_code', 'production_category', 'version'), name='unique_feed_rule_version')],
            },
        ),
        migrations.CreateModel(
            name='FeedCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inputs', models.JSONField()),
                ('result', models.JSONField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('MISSING_CONFIGURATION', 'Missing configuration'), ('INVALID', 'Invalid')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_calculations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='feed.feedrule')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
