/* Sunlit Credential dashboard: one responsive shell exposes each RBAC workspace through content states that mirror the protected backend domains. */
import { Activity, ArrowRight, BadgeCheck, Bell, BookOpen, CircleDollarSign, ClipboardCheck, HeartPulse, MessageSquareText, Plus, ShieldCheck, ShoppingBag, Stethoscope, UsersRound } from "lucide-react";
import { Link, useParams } from "wouter";
import { DashboardShell } from "@/components/DashboardShell";
import { CredentialSeal } from "@/components/CredentialSeal";

const moduleInfo: Record<string,{eyebrow:string;title:string;copy:string;icon:typeof Activity;action:string;notice?:string}> = {
  overview:{eyebrow:"Care overview",title:"Good morning. Your care space is ready.",copy:"A private place to keep track of animal care, verified connections, and practical next steps.",icon:Activity,action:"Add an animal"},
  animals:{eyebrow:"Animals & records",title:"Care information that stays with the right people.",copy:"Add animals, review protected records, and manage the grants that let a professional contribute to care.",icon:HeartPulse,action:"Add an animal",notice:"Record access is granted deliberately and can be revoked from this workspace."},
  messages:{eyebrow:"Secure messages",title:"Conversations connected to care.",copy:"Message only within the secure relationships created in VetKonnect. Keep urgent care decisions with an accessible professional.",icon:MessageSquareText,action:"Start a conversation",notice:"Messaging is not an emergency channel."},
  community:{eyebrow:"Community",title:"Practical experience, with boundaries.",copy:"Read, share, report, and block with a moderated community experience that respects safety and privacy.",icon:UsersRound,action:"Create a post"},
  credentials:{eyebrow:"Professional credentials",title:"Build a verification signal people can inspect.",copy:"Upload supporting documents, track KYC review, and activate a verification badge only after approval.",icon:BadgeCheck,action:"View badge plans",notice:"Badge visibility requires approved KYC and an active paid subscription."},
  marketplace:{eyebrow:"Marketplace",title:"Care supplies in the same clear view.",copy:"Browse products, manage vendor inventory where authorised, and keep inquiries attached to accountable listings.",icon:ShoppingBag,action:"Browse products"},
  tools:{eyebrow:"Care tools",title:"Decision support, thoughtfully bounded.",copy:"Use feed calculations and disease support to create better questions and a clearer next step — never to replace a veterinary diagnosis.",icon:BookOpen,action:"Start a calculation",notice:"If an animal may be severely ill or in danger, seek direct veterinary help."},
  billing:{eyebrow:"Billing",title:"Your verification subscription, clearly tracked.",copy:"Review weekly, monthly, or yearly badge-plan options and payment history. ClickPesa confirmation activates a valid paid badge.",icon:CircleDollarSign,action:"View payment history"},
  kyc:{eyebrow:"KYC centre",title:"Verification starts with complete information.",copy:"Follow the credential checklist and application status so the review team can assess your professional profile accurately.",icon:ClipboardCheck,action:"Upload credential"},
};

const Metric=({icon:Icon,label,value,accent}:{icon:typeof Activity;label:string;value:string;accent?:boolean})=><article className="rounded-2xl border border-[#e5dac5] bg-white p-4 shadow-[0_12px_26px_-24px_rgba(44,76,61,.4)]"><div className="flex items-start justify-between"><p className="text-[10px] font-extrabold uppercase tracking-[.13em] text-[#8c7c59]">{label}</p><Icon size={16} className={accent?"text-[#b78a38]":"text-[#315d49]"}/></div><p className="mt-5 text-2xl font-extrabold tracking-[-.05em] text-[#244c3d]">{value}</p></article>;

export default function Dashboard(){const params=useParams<{module?:string}>();const key=params.module??"overview";const current=moduleInfo[key]??moduleInfo.overview;const Icon=current.icon;return <DashboardShell><div className="care-contours min-h-[calc(100vh-72px)] p-5 sm:p-8 lg:p-10"><section className="care-contours-dark relative overflow-hidden rounded-[1.8rem] bg-[#244c3d] p-6 text-[#fffaf0] sm:p-8"><div className="relative flex flex-col justify-between gap-7 sm:flex-row sm:items-start"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#e5c46b]">{current.eyebrow}</p><h1 className="display mt-4 max-w-2xl text-4xl leading-[.95] sm:text-5xl">{current.title}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-[#d4ded5]">{current.copy}</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#f0dcab] text-[#745215]">{key === "credentials" ? <CredentialSeal size={25}/> : <Icon size={23}/>}</span></div><button className="gold-button relative mt-7">{current.action} <Plus size={16}/></button></section>
  {current.notice&&<div className="mt-5 flex gap-3 rounded-2xl border border-[#ead4a2] bg-[#fff6df] p-4 text-sm font-semibold leading-6 text-[#665431]"><ShieldCheck size={19} className="mt-0.5 shrink-0 text-[#a87822]"/>{current.notice}</div>}
  {key==="overview"?<Overview/>:<ModuleContent module={key}/>}</div></DashboardShell>}

function Overview(){return <><section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={HeartPulse} label="Animals in care" value="0"/><Metric icon={MessageSquareText} label="Open conversations" value="0"/><Metric icon={Bell} label="Unread updates" value="0" accent/><Metric icon={ShieldCheck} label="Record grants" value="0"/></section><section className="mt-6 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><article className="rounded-[1.5rem] border border-[#e5dac5] bg-white p-6"><div className="flex items-center justify-between"><div><p className="eyebrow !text-[9px]">Your next step</p><h2 className="mt-3 text-xl font-extrabold tracking-[-.04em] text-[#244c3d]">Start your private animal care record.</h2></div><HeartPulse className="text-[#b78a38]"/></div><p className="mt-3 max-w-xl text-sm leading-7 text-[#68776e]">Add an animal when you are ready. Records remain owner-scoped until you explicitly grant access to a professional.</p><Link href="/portal/animals" className="text-button mt-5">Open animal records <ArrowRight size={15}/></Link></article><article className="rounded-[1.5rem] bg-[#f0e2c2] p-6"><BadgeCheck className="text-[#946b24]"/><p className="mt-10 text-xl font-extrabold tracking-[-.04em] text-[#244c3d]">Professional on VetKonnect?</p><p className="mt-3 text-sm leading-6 text-[#506356]">Complete KYC before requesting a verification badge.</p><Link href="/portal/kyc" className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-[#8a6420]">Open KYC centre <ArrowRight size={15}/></Link></article></section></>}
function ModuleContent({module}:{module:string}){const samples:Record<string,string[]>={animals:["No animals have been added yet.","Create an animal profile to organise protected records."],messages:["No conversations yet.","Start a secure conversation only with an available VetKonnect connection."],community:["Your community activity will appear here.","Use reports and blocks when a post or interaction crosses a safety boundary."],credentials:["KYC documents and review state will appear here.","Approved veterinarians can then select a ClickPesa badge plan."],marketplace:["Browse the public catalogue or manage your authorised vendor products.","Product inquiries stay connected to vendor listings."],tools:["No saved calculations or assessments yet.","Your tool history is private to your authenticated account."],billing:["No badge subscription has been activated.","Select a plan only after your KYC status is approved."],kyc:["No professional application is in review.","Complete your profile and upload eligible credentials to begin." ]};return <section className="mt-6 rounded-[1.5rem] border border-[#e5dac5] bg-white p-6"><p className="eyebrow !text-[9px]">Private data view</p><div className="mt-7 grid gap-4 md:grid-cols-2">{(samples[module]??samples.animals).map((copy,i)=><div key={copy} className="rounded-2xl bg-[#faf6ee] p-5"><span className="text-xs font-extrabold text-[#b78a38]">0{i+1}</span><p className="mt-4 text-sm font-bold leading-6 text-[#405b4c]">{copy}</p></div>)}</div><button className="ink-button mt-6">Refresh securely <ArrowRight size={15}/></button></section>}
