/* Sunlit Credential home: an editorial care narrative uses chosen context, depth, and visible proof to make the platform feel operational from the first visit. */
import { ArrowRight, Check, ChevronRight, HeartPulse, MapPin, ShieldCheck, Sparkles, Stethoscope, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { SiteShell, SearchStrip } from "@/components/SiteShell";
import { journeyCards, services } from "@/lib/catalog";
import { CredentialSeal } from "@/components/CredentialSeal";
import { OrbitProgress, SectionReveal, TiltSurface } from "@/components/InteractivePrimitives";
import { useState } from "react";

const contexts = [
  { name: "Home companion", note: "Private animal profiles, routine notes, and a direct route to verified care.", href: "/find-care", icon: HeartPulse },
  { name: "Farm & livestock", note: "Practical planning tools, local discovery, and a shared view of everyday care work.", href: "/tools", icon: UsersRound },
  { name: "Professional practice", note: "A KYC-led path for professionals who want their evidence and availability easier to inspect.", href: "/professionals", icon: Stethoscope },
];

export default function Home() { const [context, setContext] = useState(0); const active = contexts[context]; const ActiveIcon = active.icon; return <SiteShell><main>
  <section className="care-contours relative overflow-hidden border-b border-[#eadfca] bg-[#f5eedf]"><div className="absolute inset-0 contour opacity-20"/><div className="container relative grid gap-10 pb-12 pt-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-16 lg:pb-16 lg:pt-16"><div className="relative z-10"><p className="eyebrow">Tanzania & Zanzibar care network</p><h1 className="display mt-5 max-w-xl text-[3.15rem] leading-[.92] text-[#244c3d] sm:text-7xl">Care that knows <em className="text-[#b78a38]">where</em> you are.</h1><p className="mt-6 max-w-md text-base leading-7 text-[#53675b]">Find verified veterinary professionals, organise animal care, and make the next practical step with confidence.</p><div className="mt-8 max-w-xl"><SearchStrip/><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-[#526c5b]"><span className="flex items-center gap-1.5"><CredentialSeal size={12}/>Verification status stays visible</span><span className="flex items-center gap-1.5"><MapPin size={15} className="text-[#b78a38]"/>Local search across regions</span></div></div><div className="mt-8 flex flex-wrap gap-3"><Link href="/find-care" className="ink-button">Find verified care <ArrowRight size={16}/></Link><Link href="/register" className="text-button">Create your care space</Link></div></div>
  <div className="relative min-h-[390px] lg:min-h-[560px]"><div className="absolute -right-8 -top-5 h-44 w-44 rounded-full bg-[#f3d986]/50 blur-3xl"/><div className="absolute inset-0 rounded-[2rem] bg-[#e3d1a2]"/><img src="/manus-storage/vetkonnect-hero-care_23381f6a.jpg" alt="Veterinarian attending to a dog and its owner" className="absolute inset-0 h-full w-full rounded-[2rem] object-cover"/><TiltSurface className="absolute bottom-5 left-5 right-5 flex items-center justify-between rounded-2xl border border-white/50 bg-[#fffdf8]/90 p-4 backdrop-blur-md"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#9c7837]">A clearer standard</p><p className="mt-1 text-sm font-extrabold text-[#244c3d]">Verification starts with visible proof.</p></div><span className="pulse-halo grid h-11 w-11 place-items-center rounded-full bg-[#244c3d] text-[#f6d985]"><ShieldCheck size={21}/></span></TiltSurface></div></div></section>
  <section className="container py-16 md:py-24"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Choose your starting point</p><h2 className="display mt-4 max-w-sm text-5xl leading-[.97] text-[#244c3d]">One network, shaped around the work you do.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#68776e]">Select a care context to see the most useful next route. Account profile choices can be revisited later in the profile studio.</p><div className="mt-7 grid gap-2">{contexts.map((item, index) => { const Icon = item.icon; return <button key={item.name} onClick={() => setContext(index)} className={`flex items-center gap-3 rounded-2xl p-4 text-left transition ${context === index ? "bg-[#244c3d] text-white shadow-[0_18px_32px_-24px_rgba(36,76,61,.7)]" : "border border-[#eadfca] bg-white text-[#315d49] hover:border-[#d6b56f]"}`}><span className={`grid h-9 w-9 place-items-center rounded-xl ${context === index ? "bg-[#f2d48d] text-[#244c3d]" : "bg-[#f6ecd7] text-[#8a6527]"}`}><Icon size={17}/></span><span className="text-sm font-extrabold">{item.name}</span><ChevronRight size={16} className="ml-auto"/></button>; })}</div></div><TiltSurface className="relative overflow-hidden rounded-[1.9rem] bg-[#244c3d] p-7 text-[#fffaf0] sm:p-9"><div className="depth-grid absolute inset-0 opacity-25"/><div className="relative grid gap-7 sm:grid-cols-[1fr_auto] sm:items-center"><div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#f2d48d] text-[#244c3d]"><ActiveIcon size={22}/></span><p className="mt-8 text-[10px] font-extrabold uppercase tracking-[.16em] text-[#e5c46b]">Your selected route</p><h3 className="display mt-3 text-4xl leading-[.95]">{active.name}</h3><p className="mt-4 max-w-md text-sm leading-7 text-[#d4ded5]">{active.note}</p><Link href={active.href} className="gold-button mt-7">Explore this route <ArrowRight size={15}/></Link></div><OrbitProgress value={(context + 1) * 25} label="Route" detail="Selected context"/></div></TiltSurface></div></section>
  <section className="container pb-16 md:pb-24"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">The network</p><h2 className="display mt-4 max-w-sm text-5xl leading-[.97] text-[#244c3d]">More than a directory, without losing the basics.</h2><Link href="/find-care" className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-[#a4782d]">Explore live-feeling discovery <ChevronRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{services.map(({icon: Icon,title,description}, index) => <SectionReveal key={title} className="soft-card group" style={{ transitionDelay: `${index * 45}ms` }}><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#f6ecd7] text-[#9c742c] group-hover:bg-[#244c3d] group-hover:text-[#f2d48d]"><Icon size={20}/></span><h3 className="mt-5 text-base font-extrabold text-[#244c3d]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#68776e]">{description}</p></SectionReveal>)}</div></div></section>
  <section className="care-contours-dark bg-[#244c3d] py-16 text-[#fffaf0] md:py-24"><div className="container grid gap-10 lg:grid-cols-[.92fr_1.08fr]"><div><p className="eyebrow !text-[#e7cb84]">Care begins with trust</p><h2 className="display mt-5 text-5xl leading-[.96] sm:text-6xl">The badge means a professional has been checked.</h2><p className="mt-6 max-w-md leading-7 text-[#d4dfd5]">A VetKonnect verification badge appears only when a veterinarian’s KYC status and active paid credential are valid. It is a signal you can inspect — not a promise we hide.</p><Link href="/professionals" className="gold-button mt-8">Explore professional verification <ArrowRight size={16}/></Link></div><div className="relative min-h-[390px] overflow-hidden rounded-[2rem]"><img src="/manus-storage/vetkonnect-verified-care_61e4d070.jpg" alt="Veterinarian speaking with an animal owner" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-x-5 bottom-5 rounded-2xl bg-[#fffaf0] p-5 text-[#244c3d]"><div className="flex items-center gap-3"><CredentialSeal size={22}/><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#9b7839]">VetKonnect verified</p><p className="mt-1 text-sm font-extrabold">Credentials, expiry, and ongoing status are checked.</p></div></div></div></div></div></section>
  <section className="container py-16 md:py-24"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">A connected care route</p><h2 className="display mt-4 max-w-xl text-5xl leading-[.98] text-[#244c3d]">From a first question to a better routine.</h2></div><p className="max-w-sm text-sm leading-7 text-[#68776e]">The platform makes ordinary care tasks easier to track while preserving the limits of digital advice.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{journeyCards.map(({number,title,body,href}) => <Link key={number} href={href} className="group tilt-surface rounded-[1.6rem] border border-[#e8dcc7] bg-white p-6"><span className="text-xs font-extrabold tracking-[.16em] text-[#b78a38]">{number}</span><h3 className="mt-8 text-xl font-extrabold tracking-[-.04em] text-[#244c3d]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#68776e]">{body}</p><span className="mt-7 flex items-center gap-2 text-sm font-extrabold text-[#a4782d]">Explore <ArrowRight size={15} className="transition group-hover:translate-x-1"/></span></Link>)}</div></section>
  <section className="container pb-16 md:pb-24"><div className="overflow-hidden rounded-[2rem] bg-[#f2e4c8] p-6 sm:p-10"><div className="grid gap-8 md:grid-cols-[1fr_.8fr] md:items-center"><div><p className="eyebrow">For farms, homes, and teams</p><h2 className="display mt-4 max-w-lg text-5xl leading-[.98] text-[#244c3d]">Healthy animals are a shared, everyday practice.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#53675b]">Build a private care space, then access guidance, records, trusted suppliers, and a community that understands the work.</p><div className="mt-6 flex items-center gap-2 text-xs font-bold text-[#5e6f63]"><Check size={14} className="text-[#9b7531]"/>Role choice moves to the profile studio after sign-up.</div><Link href="/register" className="ink-button mt-7">Create your care space <ArrowRight size={16}/></Link></div><div className="relative overflow-hidden rounded-[1.5rem]"><img src="/manus-storage/vetkonnect-livestock_3cc5b801.jpg" alt="Healthy cattle and a farmer in Tanzania" className="h-72 w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#244c3d]/60 to-transparent"/><p className="absolute bottom-5 left-5 right-5 text-sm font-extrabold leading-6 text-white">Tools should clarify the next conversation, not substitute a professional diagnosis.</p></div></div></div></section>
  </main></SiteShell>; }
