/* Sunlit Credential home: offset editorial panels use warm photographic light to make trusted care feel both premium and accessible. */
import { ArrowRight, ChevronRight, HeartPulse, MapPin, ShieldCheck, Stethoscope } from "lucide-react";
import { Link } from "wouter";
import { SiteShell, SearchStrip } from "@/components/SiteShell";
import { journeyCards, services } from "@/lib/catalog";
import { CredentialSeal } from "@/components/CredentialSeal";

export default function Home() { return <SiteShell><main>
  <section className="care-contours relative overflow-hidden border-b border-[#eadfca] bg-[#f5eedf]"><div className="absolute inset-0 contour opacity-20"/><div className="container relative grid gap-10 pb-12 pt-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-16 lg:pb-16 lg:pt-16"><div className="relative z-10"><p className="eyebrow">Tanzania & Zanzibar care network</p><h1 className="display mt-5 max-w-xl text-[3.15rem] leading-[.92] text-[#244c3d] sm:text-7xl">Care that knows <em className="text-[#b78a38]">where</em> you are.</h1><p className="mt-6 max-w-md text-base leading-7 text-[#53675b]">Find verified veterinary professionals, organise animal care, and make the next practical step with confidence.</p><div className="mt-8 max-w-xl"><SearchStrip/><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-[#526c5b]"><span className="flex items-center gap-1.5"><CredentialSeal size={12}/>KYC-reviewed professionals</span><span className="flex items-center gap-1.5"><MapPin size={15} className="text-[#b78a38]"/>Local search across regions</span></div></div><div className="mt-8 flex flex-wrap gap-3"><Link href="/find-care" className="ink-button">Find verified care <ArrowRight size={16}/></Link><Link href="/professionals" className="text-button">Join as a professional</Link></div></div>
  <div className="relative min-h-[390px] lg:min-h-[560px]"><div className="absolute inset-0 rounded-[2rem] bg-[#e3d1a2]"/><img src="/manus-storage/vetkonnect-hero-care_23381f6a.jpg" alt="Veterinarian attending to a dog and its owner" className="absolute inset-0 h-full w-full rounded-[2rem] object-cover"/><div className="absolute bottom-5 left-5 right-5 flex items-center justify-between rounded-2xl border border-white/50 bg-[#fffdf8]/90 p-4 backdrop-blur-md"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#9c7837]">A clearer standard</p><p className="mt-1 text-sm font-extrabold text-[#244c3d]">Verified care starts with visible proof.</p></div><span className="grid h-11 w-11 place-items-center rounded-full bg-[#244c3d] text-[#f6d985]"><ShieldCheck size={21}/></span></div></div></div></section>
  <section className="container py-18 md:py-24"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">The network</p><h2 className="display mt-4 max-w-sm text-5xl leading-[.97] text-[#244c3d]">One place for the care around your animal.</h2><Link href="/about" className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-[#a4782d]">How VetKonnect works <ChevronRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{services.map(({icon: Icon,title,description}) => <article key={title} className="soft-card group"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#f6ecd7] text-[#9c742c] group-hover:bg-[#244c3d] group-hover:text-[#f2d48d]"><Icon size={20}/></span><h3 className="mt-5 text-base font-extrabold text-[#244c3d]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#68776e]">{description}</p></article>)}</div></div></section>
  <section className="care-contours-dark bg-[#244c3d] py-16 text-[#fffaf0] md:py-24"><div className="container grid gap-10 lg:grid-cols-[.92fr_1.08fr]"><div><p className="eyebrow !text-[#e7cb84]">Care begins with trust</p><h2 className="display mt-5 text-5xl leading-[.96] sm:text-6xl">The badge means a professional has been checked.</h2><p className="mt-6 max-w-md leading-7 text-[#d4dfd5]">A VetKonnect verification badge appears only when a veterinarian’s KYC status and active paid credential are valid. It is a signal you can inspect — not a promise we hide.</p><Link href="/professionals" className="gold-button mt-8">Explore professional verification <ArrowRight size={16}/></Link></div><div className="relative min-h-[390px] overflow-hidden rounded-[2rem]"><img src="/manus-storage/vetkonnect-verified-care_61e4d070.jpg" alt="Veterinarian speaking with an animal owner" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-x-5 bottom-5 rounded-2xl bg-[#fffaf0] p-5 text-[#244c3d]"><div className="flex items-center gap-3"><CredentialSeal size={22}/><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#9b7839]">VetKonnect verified</p><p className="mt-1 text-sm font-extrabold">Credentials, expiry, and ongoing status are checked.</p></div></div></div></div></div></section>
  <section className="container py-18 md:py-24"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">A connected care route</p><h2 className="display mt-4 max-w-xl text-5xl leading-[.98] text-[#244c3d]">From a first question to a better routine.</h2></div><p className="max-w-sm text-sm leading-7 text-[#68776e]">The platform is designed to make the ordinary tasks of animal care easier to track, while preserving the limits of digital advice.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{journeyCards.map(({number,title,body,href}) => <Link key={number} href={href} className="group rounded-[1.6rem] border border-[#e8dcc7] bg-white p-6 transition hover:-translate-y-1 hover:shadow-[0_24px_45px_-33px_rgba(44,76,61,.45)]"><span className="text-xs font-extrabold tracking-[.16em] text-[#b78a38]">{number}</span><h3 className="mt-8 text-xl font-extrabold tracking-[-.04em] text-[#244c3d]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#68776e]">{body}</p><span className="mt-7 flex items-center gap-2 text-sm font-extrabold text-[#a4782d]">Explore <ArrowRight size={15} className="transition group-hover:translate-x-1"/></span></Link>)}</div></section>
  <section className="container pb-18 md:pb-24"><div className="overflow-hidden rounded-[2rem] bg-[#f2e4c8] p-6 sm:p-10"><div className="grid gap-8 md:grid-cols-[1fr_.8fr] md:items-center"><div><p className="eyebrow">For farms, homes, and teams</p><h2 className="display mt-4 max-w-lg text-5xl leading-[.98] text-[#244c3d]">Healthy animals are a shared, everyday practice.</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#53675b]">Build a private care space for your animals, then access guidance, records, trusted suppliers, and a community that understands the work.</p><Link href="/register" className="ink-button mt-7">Create your care space <ArrowRight size={16}/></Link></div><div className="relative overflow-hidden rounded-[1.5rem]"><img src="/manus-storage/vetkonnect-livestock_3cc5b801.jpg" alt="Healthy cattle and a farmer in Tanzania" className="h-72 w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#244c3d]/60 to-transparent"/><p className="absolute bottom-5 left-5 right-5 text-sm font-extrabold leading-6 text-white">Tools should clarify the next conversation, not substitute a professional diagnosis.</p></div></div></div></section>
  </main></SiteShell>; }
