# Generated by Django 5.2.17 on 2026-08-15 07:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('territory', models.CharField(choices=[('MAINLAND', 'Tanzania Mainland'), ('ZANZIBAR', 'Zanzibar')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['territory', 'name'],
                'indexes': [models.Index(fields=['territory', 'is_active'], name='locations_r_territo_58d131_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='locations.region')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('territory', models.CharField(choices=[('MAINLAND', 'Tanzania Mainland'), ('ZANZIBAR', 'Zanzibar')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('districts', models.ManyToManyField(blank=True, related_name='service_areas', to='locations.district')),
                ('regions', models.ManyToManyField(blank=True, related_name='service_areas', to='locations.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='locations.district')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-12.0')), django.core.validators.MaxValueValidator(Decimal('-0.5'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('29.0')), django.core.validators.MaxValueValidator(Decimal('41.0'))])),
                ('public_radius_km', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='locations.ward')),
            ],
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'is_active'], name='locations_d_region__5a5a18_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'code'), name='unique_district_code_per_region'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['district', 'is_active'], name='locations_w_distric_7d2849_idx'),
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('district', 'code'), name='unique_ward_code_per_district'),
        ),
        migrations.AddIndex(
            model_name='locality',
            index=models.Index(fields=['ward', 'is_active'], name='locations_l_ward_id_4bd4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='locality',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_6c554a_idx'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('ward', 'name'), name='unique_locality_per_ward'),
        ),
    ]
