# Generated by Django 5.2.17 on 2026-08-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['name', 'id']},
        ),
    ]
