# Generated by Django 5.2.17 on 2026-08-24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=120)),
                ('model_version', models.CharField(max_length=40)),
                ('is_enabled', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider_key'],
            },
        ),
        migrations.CreateModel(
            name='AIFeatureConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=40, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('requires_human_review_on_urgent', models.BooleanField(default=True)),
                ('allowed_context_fields', models.JSONField(default=list, help_text='Allowlist of field names permitted to leave the process boundary for this feature.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='ai.aiproviderconfig')),
            ],
            options={
                'ordering': ['feature_key'],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.CharField(max_length=40)),
                ('provider_key', models.CharField(blank=True, default='', max_length=40)),
                ('model_version', models.CharField(blank=True, default='', max_length=40)),
                ('input_hash', models.CharField(max_length=64)),
                ('redacted_input', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FALLBACK', 'Fallback'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], max_length=16)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('human_review_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['user', 'feature_key'], name='ai_aiintera_user_id_1f6c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['human_review_status'], name='ai_aiintera_human_r_9b2d3e_idx'),
        ),
    ]
