# Generated by Django 5.2.17 on 2026-08-15 07:35

import django.db.models.deletion
import notifications.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=180)),
                ('template_key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(max_length=8000)),
                ('payload', models.JSONField(default=dict)),
                ('channel', models.CharField(choices=[('IN_APP', 'In app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], default='IN_APP', max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], default='QUEUED', max_length=16)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed')], max_length=16)),
                ('response_metadata', models.JSONField(default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notification')),
            ],
            options={
                'ordering': ['-attempted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(default='sw-TZ', max_length=12)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
                ('enabled_channels', models.JSONField(default=notifications.models.default_enabled_channels)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('marketing_enabled', models.BooleanField(default=False)),
                ('clinical_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event_key', 'channel'), name='unique_notification_event_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationdeliveryattempt',
            constraint=models.UniqueConstraint(fields=('notification', 'attempt_number'), name='unique_notification_attempt'),
        ),
    ]
